# Generated by Django 4.2.16 on 2024-12-22 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tebak_angka', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_content', models.TextField()),
                ('finish_reason', models.CharField(max_length=20)),
                ('avg_logprobs', models.FloatField(blank=True, null=True)),
                ('prompt_token_count', models.IntegerField()),
                ('candidates_token_count', models.IntegerField()),
                ('total_token_count', models.IntegerField()),
                ('model_version', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
