# Generated by Django 4.2.16 on 2024-12-25 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tebak_angka', '0004_geminilog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('requests_today', models.IntegerField(default=0)),
                ('tokens_today', models.IntegerField(default=0)),
                ('last_reset', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
