# Generated by Django 4.2.16 on 2025-01-16 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('skills', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='InterviewStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
                ('score', models.FloatField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_hr.candidate')),
            ],
        ),
    ]
